[package]
name = "RUSTSEC-2020-0097"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "=0.9.0"

[profile.dev]
debug = true
opt-level = 0