[package]
name = "RUSTSEC-2022-0078"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "=3.11.0", features = ["allocator_api", "collections"] }