[package]
name = "RUSTSEC-2020-0060"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { path = "futures-rs-0.3.3/futures" }